### ISSUE TITLE
Sensitivities not returned by model simulation

### ISSUE THREAD

**Issue by thomassligon** [AMICI-developer/AMICI#4]
The simulation of a model is not returning SX or SY. This might be a little bug, or just a user error. Details are in the attachment.
[error-2015-11-17.docx](https://github.com/AMICI-developer/AMICI/files/36671/error-2015-11-17.docx)

**Comment by thomassligon** [comment]
...and here are the other attachments (model).

[simulate_M1Trivial.m.txt](https://github.com/AMICI-developer/AMICI/files/36673/simulate_M1Trivial.m.txt)

[M1Trivial.m.txt](https://github.com/AMICI-developer/AMICI/files/36675/M1Trivial.m.txt)

**Comment by FFroehlich** [comment]
this should be fixed in the newest revision
